# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d1eriO6NAfzuMtL+zYbwmZ3u6PihC6TJQ3IPO3VYyltCQ2qteQAEzUaF6V1ruNwUBPYw1yuPAqmH3HXeGL7ONMGHH7jdP9F9AgZMJQTnF4H/1j7Crxer+XFtqeN2W8XwtrqFKzFAPtXExraORoWRKwvZZ31r7GgwKRxQFdVzjG5jhxhCjp3Vv7gpOGebiZcaKNri7gNDFHp4ti3HF1wqeg7+sdYL9BRu/kuLo0Dijgc446KiCmMgYB+HJrhBGQRtojYFHi25k9iE8OsGN3Iw/vWdno0CnHkMI/nwoTQq5MWPupwyIm7cJHDfZBKEA/EqgLpE71+/4NeD2O/Mo7aTnPWOze2cqrWWfSJr5A9si8bO4jW/xaMFv91xr7tfu+tgVT6iH7hmEKJhoXTKzNR1tJmLpsOkjOMIsQe9oWVlrKNZpCriooLI7rfyavl1uKNRT/SNOagcBt3mjc4lmEvtvQT+5LUbCHh4j1CMKnKuvIfAqXS8WLWYUu4h3oDShZBh0WJN/+coGr2MHWppPr/CPfMo2mGufpb7Wu+tljG8xwpAQbJAhnmnX+IOJHu0ZWZT2MuKh4NeWAlxo0yr+3Kt0c5LxqwwISm+ujXLk2bFaJ2nhYeaR/G4XWTsgq48WYkD72Z4oBhEQ3tuiGE9p6DCWJWw31bPxrVhOPfIClhOg1U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
