appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JFem8WhzWHjmMZFRdPGEUewQh3XGE8rchUolmUYKSH0dVD/m1CdGan9GukWx575T96y9MqCB/9YdtiMAGVzZN7U2FCByBjlKH6KMBN2jqh5NEfxSeDvtPooauHg221MBmAY/Vm59BzfCG0YyQehJC6GUGnKwTi7JBshwoHeOToNIFPBINrUyOaPksoQAJt5lKDNkuHSP540UgJqs+qFh6pbPHSXSbOe7hhGM/3gKKV0jhv4V/3Kj2wnCIOocE+Q8XrIVBjluCMT17WMlo66CCVmzZO6EDM2Yrp0mpFfOYiwYKtjKGhyiqfLOnRm7fpy/S4k3nrlSKhaj41DzVJcKTM9M566ShQjtieQ0Ud3XUgg4PHFO8dq3u7/PYN/60S0pGeW7PJSKMi30SO5lKboU0emDacUCxF4T4rNZrlzh7JyB2sQRlVu6hE6URV1VCzLs3+ejE7qXp+UBhQWSO19kdAnBtcMLG672mHPylTa49uXxuvPy0IIorA6vYWKX8Rjb8IdB4dWYeOveF8h9a+Kb9VA8GbZCFTudqCBNUPTawg8AI+OnWj8vqdzjLJOEgqdNfYHs9V5yYJRbIfOLBPKpzFLtGdqCy27AZT3dHHGGeYrdjsIvNdYij92VuPfvbwThdhQIEdEA2lQygmus86YdKfrmDj4m4+0rxX3oIZykbJw=}
