travis:
  secure:
    BINSTAR_TOKEN: d1eriO6NAfzuMtL+zYbwmZ3u6PihC6TJQ3IPO3VYyltCQ2qteQAEzUaF6V1ruNwUBPYw1yuPAqmH3HXeGL7ONMGHH7jdP9F9AgZMJQTnF4H/1j7Crxer+XFtqeN2W8XwtrqFKzFAPtXExraORoWRKwvZZ31r7GgwKRxQFdVzjG5jhxhCjp3Vv7gpOGebiZcaKNri7gNDFHp4ti3HF1wqeg7+sdYL9BRu/kuLo0Dijgc446KiCmMgYB+HJrhBGQRtojYFHi25k9iE8OsGN3Iw/vWdno0CnHkMI/nwoTQq5MWPupwyIm7cJHDfZBKEA/EqgLpE71+/4NeD2O/Mo7aTnPWOze2cqrWWfSJr5A9si8bO4jW/xaMFv91xr7tfu+tgVT6iH7hmEKJhoXTKzNR1tJmLpsOkjOMIsQe9oWVlrKNZpCriooLI7rfyavl1uKNRT/SNOagcBt3mjc4lmEvtvQT+5LUbCHh4j1CMKnKuvIfAqXS8WLWYUu4h3oDShZBh0WJN/+coGr2MHWppPr/CPfMo2mGufpb7Wu+tljG8xwpAQbJAhnmnX+IOJHu0ZWZT2MuKh4NeWAlxo0yr+3Kt0c5LxqwwISm+ujXLk2bFaJ2nhYeaR/G4XWTsgq48WYkD72Z4oBhEQ3tuiGE9p6DCWJWw31bPxrVhOPfIClhOg1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
